### ISSUE TITLE
Why didnt you use built-in sensors of f3discovery board

### ISSUE THREAD

**Issue by talalahsan01** [copterust/f3-eva#2]
For the f3-eva project, you are using stm32f303 and it has its own builtin gyro,mag and accel sensors which could have been used,so why didn't you use them? Rather you used another sensor. Could you give example of how they could be used to get roll, pitch and yaw and also tell me if there are issues in using built in sensors of the board.

**Comment by bofh** [comment]
Hey @talalahsan01, the STM32F303 are mixed-signal MCUs, they don’t have IMU built-in. We are using the F3 EVO Flight Controller board as our platform for this project and using it’s sensor.

**Comment by talalahsan01** [comment]
> Hey @talalahsan01, the STM32F303 are mixed-signal MCUs, they don’t have IMU built-in. We are using the F3 EVO Flight Controller board as our platform for this project and using it’s sensor.

But they do have lsm303 and l3gd20 units, can you tell me the downside of using those sensors to detect orientation in space?

**Comment by little-arhat** [comment]
@talalahsan01 hello! We don't use f3discovery board. We use [F3 EVO Flight Controller board](http://seriouslypro.com/spracingf3evo) as our platform. That board comes with STM32F303 CPU cpu and  mpu9250 (or mpu6250 in some cases) as accelerometer/gyro/compass sensor. 

We do have [drivers for lsm303](https://github.com/copterust/lsm303c/) ready, though, so it should be possible to run this code on boards with lsm303 after some tweaks.

**Comment by talalahsan01** [comment]
> @talalahsan01 hello! We don't use f3discovery board. We use [F3 EVO Flight Controller board](http://seriouslypro.com/spracingf3evo) as our platform. That board comes with STM32F303 CPU cpu and  mpu9250 (or mpu6250 in some cases) as accelerometer/gyro/compass sensor. 
> 
> We do have [drivers for lsm303](https://github.com/copterust/lsm303c/) ready, though, so it should be possible to run this code on boards with lsm303 after some tweaks. 

Ok thanks now i got it, i was confusing it with discovery board, so basically what I am stuck on is the sensor fusion algorithm, i am hoping to use l3gd20 and lsm303 to to read data (which i can at the moment), but i am stuck with sensor fusion algorithm and i found this project, and i must say it is amazing, but could you let me know how i can use this code for sensor fusion in my case, i need yaw, roll and pitch also i don't care about gimbal lock because i won't be doing any loops or extreme maneuvers.

**Comment by little-arhat** [comment]
Unless you want to use sensor fusion algos provided by device, it shouldn't matter what sensors you actually use to get data (modulo calibration). 

At the end sensor fusion algos implemented in software, like [kalman](https://github.com/copterust/f3-eva/blob/934c639c5281153fbe431e4ed599b1ef2c77fadb/src/ahrs/kalman.rs), [madgwick](https://github.com/copterust/madgwick), [dcmimu](https://github.com/copterust/dcmimu) receive raw data and don't care whether this raw data came from mpu or lsm.

**Comment by talalahsan01** [comment]
> Unless you want to use sensor fusion algos provided by device, it shouldn't matter what sensors you actually use to get data (modulo calibration). 
> 
> At the end sensor fusion algos implemented in software, like [kalman](https://github.com/copterust/f3-eva/blob/934c639c5281153fbe431e4ed599b1ef2c77fadb/src/ahrs/kalman.rs), [madgwick](https://github.com/copterust/madgwick), [dcmimu](https://github.com/copterust/dcmimu) receive raw data and don't care whether this raw data came from mpu or lsm. 

Thanks bro i will try using dcmimu for my quadcopter project because i need roll, pitch and yaw, i initially wanted to use madgwick but i am not able to use it correctly also the quaternion i was receiving just didn't seem right. Basically i am beginner in this so i don't even know what i was doing wrong. I used madgwick crate from crate.io.
